### ISSUE TITLE
support dates

### ISSUE THREAD

**Issue by cainus** [cainus/mongoJsonSchema#1]

**Comment by RangerMauve** [comment]
I noticed that there is code that mentions dates, would it be safe to assume that date support _is_ actually implemented?

**Comment by cainus** [comment]
Yeah it looks like we just never closed this, but it works: https://github.com/cainus/mongoJsonSchema/blob/master/test/index.js#L293  .  The format is rfc3339 / iso 8601 .

I'll close this now, but let me know if you have an y problems with it.

**Comment by RangerMauve** [comment]
Might want to add it to the readme, then. I'll let you know if it's working properly some time today, I think.

**Comment by RangerMauve** [comment]
Oh, also it seems that there is no `stringsToDates()` to correspond with `datesToStrings()` like you have with `idsToStrings`
